spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment_service
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      function:
        definition: paymentProcessor
        bindings:
          paymentProcessor-in-0:
            destination: order-event
          paymentProcessor-out-0:
            destination: payment-event

