spring:
  application:
    name: order-service
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order_service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update




server:
  port: 8082
